
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raido.Sukles
 */
public class Graf extends javax.swing.JFrame {

    double surfaceX, surfaceY, tileX, tileY, gap;
    int messageInt, totalTiles, totalWholeTiles, totalCutTiles,
            columnAmount, rowAmount, cornerAmount;
    String unit, messageText, messageTitle, column, row, corner, str1, str2,
            columnStr, rowStr, cornerStr;
    /**
     * Creates new form Graf
     */
    public Graf() {
        initComponents();
        ((JSpinner.DefaultEditor) spnGap.getEditor()).getTextField().setEditable(false);
        placeholders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbUnit = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnArvuta = new javax.swing.JButton();
        spnGap = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtSurfaceX = new javax.swing.JTextField();
        txtSurfaceY = new javax.swing.JTextField();
        txtTileX = new javax.swing.JTextField();
        txtTileY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Põrandaplaatide rakendus");

        cmbUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cm", "mm", "m" }));

        jLabel1.setText("Sisesta põranda mõõdud");

        jLabel2.setText("Siia kirjuta Laius");

        jLabel3.setText("ja siia Pikkus");

        jLabel4.setText("Sisesta plaadi mõõdud");

        jLabel5.setText("Siia Laius");

        jLabel6.setText("ja siia Pikkus");

        btnArvuta.setText("Arvuta");
        btnArvuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArvutaActionPerformed(evt);
            }
        });

        jLabel8.setText("Siia sisesta vuugivahe");

        jLabel9.setText("millimeetrites");

        jButton1.setText("Puhastus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel6)
                                .addGap(100, 100, 100))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(txtSurfaceX, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(txtSurfaceY, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(75, 75, 75))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnGap, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(btnArvuta)
                            .addComponent(cmbUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(226, 226, 226)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTileX, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTileY, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSurfaceX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSurfaceY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTileX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTileY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(cmbUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnGap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnArvuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArvutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArvutaActionPerformed
        if (!(txtSurfaceX.getText().isEmpty() || txtSurfaceY.getText().isEmpty() || txtTileX.getText().isEmpty() || txtTileY.getText().isEmpty())) {
            unit = String.valueOf(cmbUnit.getSelectedItem());
            //<editor-fold defaultstate="collapsed" desc="Vuugivahe teisendamine">
            switch (unit) {
                case "mm":
                    gap = Double.parseDouble(String.valueOf(spnGap.getValue()));
                    break;
                case "cm":
                    gap = Double.parseDouble(String.valueOf(spnGap.getValue())) * 0.1;
                    break;
                case "m":
                    gap = Double.parseDouble(String.valueOf(spnGap.getValue())) * 0.001;
                    break;
                default:
                    break;
            }
            //</editor-fold>

            surfaceX = Double.parseDouble(txtSurfaceX.getText());
            tileX = Double.parseDouble(txtTileX.getText());
            surfaceY = Double.parseDouble(txtSurfaceY.getText());
            tileY = Double.parseDouble(txtTileY.getText());

            PlaatideArvutamine calcY = new PlaatideArvutamine(surfaceY, tileY, gap);
            PlaatideArvutamine calcX = new PlaatideArvutamine(surfaceX, tileX, gap);

            totalTiles = calcX.getAllTiles() * calcY.getAllTiles();
            totalWholeTiles = calcX.getWholeTiles() * calcY.getWholeTiles();
            totalCutTiles = totalTiles - totalWholeTiles;

            column = calcX.getEdge() + unit + " x " + tileY + unit;             // x - 12,5x30 - 6tk - xäär   x yplaat - column
            row = tileX + unit + " x " + calcY.getEdge() + unit;                // o - 20x25   - 3tk - xplaat x yäär   - row
            corner = calcX.getEdge() + unit + " x " + calcY.getEdge() + unit;   // v - 12,5x25 - 2tk - xäär   x yäär   - corner

            columnAmount = calcX.getCutTiles() * calcY.getWholeTiles();         // x - lõigatud x (2) * terve y (3)
            rowAmount = calcX.getWholeTiles() * calcY.getCutTiles();            // o - terve x (3) * lõigatud y (1)
            cornerAmount = calcX.getCutTiles() * calcY.getCutTiles();           // v - lõigatud x (2) * lõigatud y (1)

            //<editor-fold defaultstate="collapsed" desc="String messageText">
            if (calcX.getCutTiles() > 0) {
                str1 = "\n Ritta läheb " + calcX.getAllTiles() + " plaati, millest " + calcX.getWholeTiles() + " on terved ning " + calcX.getCutTiles() + " on lõigatud.";
            } else {
                str1 = "\n Ritta läheb " + calcX.getAllTiles() + " tervet plaati.";
            }
            if (calcY.getCutTiles() > 0) {
                str2 = "\n Veergu läheb " + calcY.getAllTiles() + " plaati, millest " + calcY.getWholeTiles() + " on terved ning " + calcY.getCutTiles() + " on lõigatud.";
            } else {
                str2 = "\n Veergu läheb " + calcY.getAllTiles() + " tervet plaati.";
            }

            messageText = " Kokku läheb " + totalTiles + " plaati, millest " + totalWholeTiles + " on terved ning " + totalCutTiles + " on lõigatud." + str1 + str2;

            if (columnAmount > 0) {
                columnStr = "\n " + column + " - " + columnAmount + "tk";
                messageText = messageText + columnStr;
            }
            if (rowAmount > 0) {
                rowStr = "\n " + row + " - " + rowAmount + "tk";
                messageText = messageText + rowStr;
            }
            if (cornerAmount > 0) {
                cornerStr = "\n " + corner + " - " + cornerAmount + "tk";
                messageText = messageText + cornerStr;
            }
            messageTitle = "Põrandaplaadid";
            messageInt = 1;
        } else {
            messageText = "Arvutamiseks täitke kõik väljad!";
            messageTitle = "Teade";
            messageInt = 0;

//</editor-fold>
        }
        JOptionPane.showMessageDialog(this, messageText, messageTitle, messageInt);
    }//GEN-LAST:event_btnArvutaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtSurfaceX.setText("");
        txtSurfaceY.setText("");
        txtTileX.setText("");
        txtTileY.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

     private void placeholders() {
        TekstiValjastus tp1 = new TekstiValjastus("Laius x", txtSurfaceX);
        tp1.setForeground(Color.gray);
        TekstiValjastus tp2 = new TekstiValjastus("Pikkus y", txtSurfaceY);
        tp2.setForeground(Color.gray);
        TekstiValjastus tp3 = new TekstiValjastus("Laius x", txtTileX);
        tp3.setForeground(Color.gray);
        TekstiValjastus tp4 = new TekstiValjastus("Pikkus y", txtTileY);
        tp4.setForeground(Color.gray);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArvuta;
    private javax.swing.JComboBox<String> cmbUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner spnGap;
    private javax.swing.JTextField txtSurfaceX;
    private javax.swing.JTextField txtSurfaceY;
    private javax.swing.JTextField txtTileX;
    private javax.swing.JTextField txtTileY;
    // End of variables declaration//GEN-END:variables
}
